publicHoistPattern:
    - "*eslint*"
    - "!@marketjs/config.eslint"
linkWorkspacePackages: deep
preferWorkspacePackages: true
packages:
    - "packages/*"
    - "packages/@marketjs/*"
    - "packages/@marketjs/config/*"
    - "packages/@marketjs/react/*"
    - "packages/@marketjs/react/examples/*"
