publicHoistPattern:
    - "*eslint*"
    - "!config.eslint"
linkWorkspacePackages: deep
preferWorkspacePackages: true
packages:
    - "packages/*"
    - "packages/config/*"
    - "packages/react/*"
    - "packages/cachers/*"
catalog:
    "@typescript/native": "npm:typescript@^7.0.2"
    "typescript": "npm:@typescript/typescript6@^6.0.2"
