publicHoistPattern:
    - "*eslint*"
    - "!@paramodules/config.eslint"
linkWorkspacePackages: deep
preferWorkspacePackages: true
packages:
    - "packages/*"
    - "packages/@paramodules/*"
    - "packages/@paramodules/config/*"
    - "packages/@paramodules/react/*"
    - "packages/@paramodules/react/examples/*"
