name: Build Pkg

on:
    workflow_call:

jobs:
    build-pkg:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: |
                  pnpm run build --filter=paramodules
                  pnpm run build --filter=@paramodules/react

            - name: Upload paramodules build artifacts
              if: ${{ github.event_name == 'release' }}
              uses: actions/upload-artifact@v4
              with:
                  name: "paramodules-build"
                  path: |
                      packages/paramodules/dist

            - name: Upload @paramodules/react build artifacts
              if: ${{ github.event_name == 'release' }}
              uses: actions/upload-artifact@v4
              with:
                  name: "@paramodules-react-build"
                  path: |
                      packages/@paramodules/react/main/dist
