name: Build Pkg

on:
    workflow_call:

jobs:
    build-pkg:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        strategy:
            matrix:
                include:
                    - filter: paramodules
                      dist_path: packages/@paramodules/core/dist
                      artifact_name: paramodules-build

                    - filter: "@paramodules/react"
                      dist_path: packages/@paramodules/react/main/dist
                      artifact_name: "@paramodules-react-build"

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: pnpm install

            - name: Build ${{ matrix.filter }}
              run: pnpm run build --filter=${{ matrix.filter }}

            - name: Verify ${{ matrix.dist_path }}/index.js exists
              run: test -f "${{ matrix.dist_path }}/index.js"

            - name: Upload ${{ matrix.filter }} build artifacts
              if: ${{ github.event_name == 'release' }}
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact_name }}
                  path: ${{ matrix.dist_path }}
