name: Deploy

on:
    release:
        types: [published]

concurrency:
    group: "deploy"
    cancel-in-progress: false

jobs:
    validate-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/validate-tag

    gate:
        needs: validate-tag
        runs-on: ubuntu-latest
        if: contains(github.event.release.tag_name, '-') == false ||
            contains(github.event.release.tag_name, 'docs')
        steps:
            - name: Gate check
              run: echo "Deploy condition met"

    test:
        needs: gate
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/test

    build-docs:
        needs: gate
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v5

            - uses: ./.github/actions/setup
            - uses: ./.github/actions/build-docs
              with:
                  upload_pages_artifact: "true"

    deploy-docs:
        environment:
            name: github-pages
            url: ${{ steps.deploy-docs.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: [test, build-docs, validate-tag]
        permissions:
            pages: write # Required for deploying to GitHub Pages
            id-token: write # Required for OIDC with GitHub Pages
        steps:
            - name: Deploy to GitHub Pages
              id: deploy-docs
              uses: actions/deploy-pages@v4
