name: PR Check

on:
    pull_request:
        branches: [main]

jobs:
    pr-check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v5

            - uses: ./.github/actions/setup
            - uses: ./.github/actions/test

            - uses: ./.github/actions/build-pkg
              with:
                  filter: paramodules
                  dist_path: packages/@paramodules/core/dist

            - uses: ./.github/actions/build-pkg
              with:
                  filter: "@paramodules/react"
                  dist_path: packages/@paramodules/react/main/dist

            - uses: ./.github/actions/build-docs
