name: PR Check

on:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v5

            - uses: ./.github/actions/setup
            - uses: ./.github/actions/test

    build-pkg:
        needs: test
        strategy:
            matrix:
                include:
                    - filter: paramodules
                      dist_path: packages/@paramodules/core/dist
                    - filter: "@paramodules/react"
                      dist_path: packages/@paramodules/react/main/dist
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/build-pkg
              with:
                  filter: ${{ matrix.filter }}
                  dist_path: ${{ matrix.dist_path }}

    build-docs:
        needs: test
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/build-docs
              with:
                  upload_pages_artifact: "false"
